name: Crawl

on:
  workflow_dispatch:
  schedule:
    - cron: '18 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with: 
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run script
      run: python crawler.py
    - name: Commit files
      run: |
        git config --local user.email "zungmou@users.noreply.github.com"
        git config --local user.name "GitHub Action Crawl"
        git add .
        git commit -am "Auto update"
        git push
